# Generated by Django 3.1.5 on 2021-03-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='user',
            field=models.IntegerField(),
        ),
    ]
